# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.hint_from_organization_library import HintFromOrganizationLibrary

class TestHintFromOrganizationLibrary(unittest.TestCase):
    """HintFromOrganizationLibrary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HintFromOrganizationLibrary:
        """Test HintFromOrganizationLibrary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HintFromOrganizationLibrary`
        """
        model = HintFromOrganizationLibrary()
        if include_optional:
            return HintFromOrganizationLibrary(
                type = 'orglib',
                id = 56
            )
        else:
            return HintFromOrganizationLibrary(
                id = 56,
        )
        """

    def testHintFromOrganizationLibrary(self):
        """Test HintFromOrganizationLibrary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
