# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.finding_thread_subject import FindingThreadSubject

class TestFindingThreadSubject(unittest.TestCase):
    """FindingThreadSubject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindingThreadSubject:
        """Test FindingThreadSubject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindingThreadSubject`
        """
        model = FindingThreadSubject()
        if include_optional:
            return FindingThreadSubject(
                type = 'finding',
                task_id = 56,
                analysis_result_id = '',
                finding_id = ''
            )
        else:
            return FindingThreadSubject(
                task_id = 56,
                analysis_result_id = '',
                finding_id = '',
        )
        """

    def testFindingThreadSubject(self):
        """Test FindingThreadSubject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
