# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.picus_v2_parameters import PicusV2Parameters

class TestPicusV2Parameters(unittest.TestCase):
    """PicusV2Parameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PicusV2Parameters:
        """Test PicusV2Parameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PicusV2Parameters`
        """
        model = PicusV2Parameters()
        if include_optional:
            return PicusV2Parameters(
                source = '',
                solver = 'cvc5',
                smt_file = '',
                no_solver = True,
                no_optimization = True,
                no_range_analysis = True,
                no_linear = True,
                no_table = True,
                no_basis = True,
                no_poly = True,
                solver_timeout = 56,
                time_limit = 56,
                assume_deterministic = [
                    ''
                    ],
                enable_debug = True,
                apply_rewrites = True
            )
        else:
            return PicusV2Parameters(
                source = '',
        )
        """

    def testPicusV2Parameters(self):
        """Test PicusV2Parameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
