# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.fio_data import FIOData

class TestFIOData(unittest.TestCase):
    """FIOData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FIOData:
        """Test FIOData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FIOData`
        """
        model = FIOData()
        if include_optional:
            return FIOData(
                state_digest = 56,
                analysis_result_id = '',
                is_filtered = True,
                data = { },
                actions = [
                    audithub_sdk.models.finding_action.FindingAction(
                        action_id = '', 
                        caption = '', 
                        comment = '', 
                        created_by = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return FIOData(
                state_digest = 56,
                analysis_result_id = '',
                is_filtered = True,
                actions = [
                    audithub_sdk.models.finding_action.FindingAction(
                        action_id = '', 
                        caption = '', 
                        comment = '', 
                        created_by = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testFIOData(self):
        """Test FIOData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
