# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.issue_status_transition import IssueStatusTransition

class TestIssueStatusTransition(unittest.TestCase):
    """IssueStatusTransition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IssueStatusTransition:
        """Test IssueStatusTransition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IssueStatusTransition`
        """
        model = IssueStatusTransition()
        if include_optional:
            return IssueStatusTransition(
                issue_id = 56,
                function = '',
                from_status = '',
                to_status = '',
                extra = audithub_sdk.models.extra_function_arguments.ExtraFunctionArguments(
                    comments = '', 
                    pr = '0', 
                    commit = '', ),
                created_by = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return IssueStatusTransition(
                issue_id = 56,
                function = '',
                from_status = '',
                to_status = '',
                extra = audithub_sdk.models.extra_function_arguments.ExtraFunctionArguments(
                    comments = '', 
                    pr = '0', 
                    commit = '', ),
                created_by = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testIssueStatusTransition(self):
        """Test IssueStatusTransition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
