# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.version_patch import VersionPatch

class TestVersionPatch(unittest.TestCase):
    """VersionPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VersionPatch:
        """Test VersionPatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VersionPatch`
        """
        model = VersionPatch()
        if include_optional:
            return VersionPatch(
                delete = True,
                name = '',
                commit_hash = '',
                project_revision_hash = '',
                is_deployed = True
            )
        else:
            return VersionPatch(
        )
        """

    def testVersionPatch(self):
        """Test VersionPatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
