# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.api.v_specs_std_lib_api import VSpecsStdLibApi


class TestVSpecsStdLibApi(unittest.TestCase):
    """VSpecsStdLibApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VSpecsStdLibApi()

    def tearDown(self) -> None:
        pass

    def test_get_v_specifications_library_v_spec_library_get(self) -> None:
        """Test case for get_v_specifications_library_v_spec_library_get

        Get V Specifications Library
        """
        pass

    def test_get_v_specifications_library_version_v_spec_library_version_id_get(self) -> None:
        """Test case for get_v_specifications_library_version_v_spec_library_version_id_get

        Get V Specifications Library Version
        """
        pass


if __name__ == '__main__':
    unittest.main()
