# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.user_access_restriction import UserAccessRestriction

class TestUserAccessRestriction(unittest.TestCase):
    """UserAccessRestriction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserAccessRestriction:
        """Test UserAccessRestriction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserAccessRestriction`
        """
        model = UserAccessRestriction()
        if include_optional:
            return UserAccessRestriction(
                function = '',
                value = 56,
                detector = '',
                project_id = 56
            )
        else:
            return UserAccessRestriction(
                function = '',
        )
        """

    def testUserAccessRestriction(self):
        """Test UserAccessRestriction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
