# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.api.configuration_api import ConfigurationApi


class TestConfigurationApi(unittest.TestCase):
    """ConfigurationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigurationApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_keys_api_keys_configuration_get(self) -> None:
        """Test case for get_api_keys_api_keys_configuration_get

        Get Api Keys
        """
        pass

    def test_get_configuration_configuration_get(self) -> None:
        """Test case for get_configuration_configuration_get

        Get Configuration
        """
        pass


if __name__ == '__main__':
    unittest.main()
