# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.organization_consumption_detailed import OrganizationConsumptionDetailed

class TestOrganizationConsumptionDetailed(unittest.TestCase):
    """OrganizationConsumptionDetailed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationConsumptionDetailed:
        """Test OrganizationConsumptionDetailed
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationConsumptionDetailed`
        """
        model = OrganizationConsumptionDetailed()
        if include_optional:
            return OrganizationConsumptionDetailed(
                from_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                to_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                versions = [
                    audithub_sdk.models.version_resources.VersionResources(
                        id = 56, 
                        project_id = 56, 
                        resources = audithub_sdk.models.resources.Resources(
                            cpu_minutes = 1.337, ), 
                        tasks = [
                            audithub_sdk.models.task_resources.TaskResources(
                                id = 56, 
                                resources = audithub_sdk.models.resources.Resources(
                                    cpu_minutes = 1.337, ), 
                                steps = [
                                    audithub_sdk.models.step_resources.StepResources(
                                        code = '', 
                                        resources = , 
                                        containers = [
                                            audithub_sdk.models.container_resources.ContainerResources(
                                                code = '', 
                                                resources = , )
                                            ], )
                                    ], )
                            ], )
                    ]
            )
        else:
            return OrganizationConsumptionDetailed(
                versions = [
                    audithub_sdk.models.version_resources.VersionResources(
                        id = 56, 
                        project_id = 56, 
                        resources = audithub_sdk.models.resources.Resources(
                            cpu_minutes = 1.337, ), 
                        tasks = [
                            audithub_sdk.models.task_resources.TaskResources(
                                id = 56, 
                                resources = audithub_sdk.models.resources.Resources(
                                    cpu_minutes = 1.337, ), 
                                steps = [
                                    audithub_sdk.models.step_resources.StepResources(
                                        code = '', 
                                        resources = , 
                                        containers = [
                                            audithub_sdk.models.container_resources.ContainerResources(
                                                code = '', 
                                                resources = , )
                                            ], )
                                    ], )
                            ], )
                    ],
        )
        """

    def testOrganizationConsumptionDetailed(self):
        """Test OrganizationConsumptionDetailed"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
