# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.container_resources import ContainerResources

class TestContainerResources(unittest.TestCase):
    """ContainerResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContainerResources:
        """Test ContainerResources
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContainerResources`
        """
        model = ContainerResources()
        if include_optional:
            return ContainerResources(
                code = '',
                resources = audithub_sdk.models.resources.Resources(
                    cpu_minutes = 1.337, )
            )
        else:
            return ContainerResources(
                code = '',
                resources = audithub_sdk.models.resources.Resources(
                    cpu_minutes = 1.337, ),
        )
        """

    def testContainerResources(self):
        """Test ContainerResources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
