# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.version_resources import VersionResources

class TestVersionResources(unittest.TestCase):
    """VersionResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VersionResources:
        """Test VersionResources
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VersionResources`
        """
        model = VersionResources()
        if include_optional:
            return VersionResources(
                id = 56,
                resources = audithub_sdk.models.resources.Resources(
                    cpu_minutes = 1.337, ),
                tasks = [
                    audithub_sdk.models.task_resources.TaskResources(
                        id = 56, 
                        resources = audithub_sdk.models.resources.Resources(
                            cpu_minutes = 1.337, ), 
                        steps = [
                            audithub_sdk.models.step_resources.StepResources(
                                code = '', 
                                resources = audithub_sdk.models.resources.Resources(
                                    cpu_minutes = 1.337, ), 
                                containers = [
                                    audithub_sdk.models.container_resources.ContainerResources(
                                        code = '', 
                                        resources = , )
                                    ], )
                            ], )
                    ]
            )
        else:
            return VersionResources(
                id = 56,
                resources = audithub_sdk.models.resources.Resources(
                    cpu_minutes = 1.337, ),
                tasks = [
                    audithub_sdk.models.task_resources.TaskResources(
                        id = 56, 
                        resources = audithub_sdk.models.resources.Resources(
                            cpu_minutes = 1.337, ), 
                        steps = [
                            audithub_sdk.models.step_resources.StepResources(
                                code = '', 
                                resources = audithub_sdk.models.resources.Resources(
                                    cpu_minutes = 1.337, ), 
                                containers = [
                                    audithub_sdk.models.container_resources.ContainerResources(
                                        code = '', 
                                        resources = , )
                                    ], )
                            ], )
                    ],
        )
        """

    def testVersionResources(self):
        """Test VersionResources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
