# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.api.editor_languages_api import EditorLanguagesApi


class TestEditorLanguagesApi(unittest.TestCase):
    """EditorLanguagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EditorLanguagesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_language_editor_languages_language_id_delete(self) -> None:
        """Test case for delete_language_editor_languages_language_id_delete

        Delete Language
        """
        pass

    def test_get_language_editor_languages_language_id_get(self) -> None:
        """Test case for get_language_editor_languages_language_id_get

        Get Language
        """
        pass

    def test_get_languages_editor_languages_get(self) -> None:
        """Test case for get_languages_editor_languages_get

        Get Languages
        """
        pass

    def test_post_language_editor_languages_post(self) -> None:
        """Test case for post_language_editor_languages_post

        Post Language
        """
        pass

    def test_put_language_editor_languages_language_id_put(self) -> None:
        """Test case for put_language_editor_languages_language_id_put

        Put Language
        """
        pass


if __name__ == '__main__':
    unittest.main()
