# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.v_spec_ad_hoc import VSpecAdHoc

class TestVSpecAdHoc(unittest.TestCase):
    """VSpecAdHoc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VSpecAdHoc:
        """Test VSpecAdHoc
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VSpecAdHoc`
        """
        model = VSpecAdHoc()
        if include_optional:
            return VSpecAdHoc(
                type = 'adhoc',
                filename = '',
                contents = '',
                encoding = 'plain'
            )
        else:
            return VSpecAdHoc(
                filename = '',
                contents = '',
        )
        """

    def testVSpecAdHoc(self):
        """Test VSpecAdHoc"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
