# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.api.issues_api import IssuesApi


class TestIssuesApi(unittest.TestCase):
    """IssuesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IssuesApi()

    def tearDown(self) -> None:
        pass

    def test_batch_announce_organizations_organization_id_projects_project_id_issues_patch(self) -> None:
        """Test case for batch_announce_organizations_organization_id_projects_project_id_issues_patch

        Batch Announce
        """
        pass

    def test_export_issues_organizations_organization_id_projects_project_id_issues_export_get(self) -> None:
        """Test case for export_issues_organizations_organization_id_projects_project_id_issues_export_get

        Export Issues
        """
        pass

    def test_get_issue_organizations_organization_id_projects_project_id_issues_issue_id_get(self) -> None:
        """Test case for get_issue_organizations_organization_id_projects_project_id_issues_issue_id_get

        Get Issue
        """
        pass

    def test_get_issues_organizations_organization_id_projects_project_id_issues_get(self) -> None:
        """Test case for get_issues_organizations_organization_id_projects_project_id_issues_get

        Get Issues
        """
        pass

    def test_patch_issue_organizations_organization_id_projects_project_id_issues_issue_id_patch(self) -> None:
        """Test case for patch_issue_organizations_organization_id_projects_project_id_issues_issue_id_patch

        Patch Issue
        """
        pass

    def test_post_issue_organizations_organization_id_projects_project_id_issues_post(self) -> None:
        """Test case for post_issue_organizations_organization_id_projects_project_id_issues_post

        Post Issue
        """
        pass

    def test_post_issue_to_github_organizations_organization_id_projects_project_id_issues_issue_id_gh_issue_post(self) -> None:
        """Test case for post_issue_to_github_organizations_organization_id_projects_project_id_issues_issue_id_gh_issue_post

        Post Issue To Github
        """
        pass

    def test_post_security_advisory_to_github_organizations_organization_id_projects_project_id_issues_issue_id_gh_security_advisory_post(self) -> None:
        """Test case for post_security_advisory_to_github_organizations_organization_id_projects_project_id_issues_issue_id_gh_security_advisory_post

        Post Security Advisory To Github
        """
        pass

    def test_put_issue_organizations_organization_id_projects_project_id_issues_issue_id_put(self) -> None:
        """Test case for put_issue_organizations_organization_id_projects_project_id_issues_issue_id_put

        Put Issue
        """
        pass


if __name__ == '__main__':
    unittest.main()
