# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.active_organization_users import ActiveOrganizationUsers

class TestActiveOrganizationUsers(unittest.TestCase):
    """ActiveOrganizationUsers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActiveOrganizationUsers:
        """Test ActiveOrganizationUsers
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActiveOrganizationUsers`
        """
        model = ActiveOrganizationUsers()
        if include_optional:
            return ActiveOrganizationUsers(
                registered = [
                    audithub_sdk.models.registered_user.RegisteredUser(
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = '', 
                        ignored_for_quota = True, )
                    ],
                invited = [
                    audithub_sdk.models.invited_user.InvitedUser(
                        email = '', 
                        name = '', 
                        invited_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        invited_by = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                users = {
                    'key' : audithub_sdk.models.included_user_info.IncludedUserInfo(
                        name = '', )
                    }
            )
        else:
            return ActiveOrganizationUsers(
                registered = [
                    audithub_sdk.models.registered_user.RegisteredUser(
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = '', 
                        ignored_for_quota = True, )
                    ],
                invited = [
                    audithub_sdk.models.invited_user.InvitedUser(
                        email = '', 
                        name = '', 
                        invited_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        invited_by = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                users = {
                    'key' : audithub_sdk.models.included_user_info.IncludedUserInfo(
                        name = '', )
                    },
        )
        """

    def testActiveOrganizationUsers(self):
        """Test ActiveOrganizationUsers"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
