# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.api.subscriptions_api import SubscriptionsApi


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_get_current_organization_subscriptions_organizations_organization_id_subscriptions_get(self) -> None:
        """Test case for get_current_organization_subscriptions_organizations_organization_id_subscriptions_get

        Get Current Organization Subscriptions
        """
        pass

    def test_get_organization_subscription_organizations_organization_id_subscriptions_subscription_id_get(self) -> None:
        """Test case for get_organization_subscription_organizations_organization_id_subscriptions_subscription_id_get

        Get Organization Subscription
        """
        pass

    def test_patch_subscription_organizations_organization_id_subscriptions_subscription_id_patch(self) -> None:
        """Test case for patch_subscription_organizations_organization_id_subscriptions_subscription_id_patch

        Patch Subscription
        """
        pass

    def test_post_organization_subscription_organizations_organization_id_subscriptions_post(self) -> None:
        """Test case for post_organization_subscription_organizations_organization_id_subscriptions_post

        Post Organization Subscription
        """
        pass

    def test_put_organization_subscription_organizations_organization_id_subscriptions_subscription_id_put(self) -> None:
        """Test case for put_organization_subscription_organizations_organization_id_subscriptions_subscription_id_put

        Put Organization Subscription
        """
        pass


if __name__ == '__main__':
    unittest.main()
