# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.task_patch import TaskPatch

class TestTaskPatch(unittest.TestCase):
    """TaskPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskPatch:
        """Test TaskPatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskPatch`
        """
        model = TaskPatch()
        if include_optional:
            return TaskPatch(
                action = 'cancel'
            )
        else:
            return TaskPatch(
                action = 'cancel',
        )
        """

    def testTaskPatch(self):
        """Test TaskPatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
