# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.user_for_admin import UserForAdmin

class TestUserForAdmin(unittest.TestCase):
    """UserForAdmin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserForAdmin:
        """Test UserForAdmin
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserForAdmin`
        """
        model = UserForAdmin()
        if include_optional:
            return UserForAdmin(
                id = '',
                name = '',
                email = '',
                rights = [
                    ''
                    ],
                disable_online_notifications = True,
                disable_digest_notifications = True,
                onboarded_via = '',
                tour_done = [
                    ''
                    ],
                captcha = True
            )
        else:
            return UserForAdmin(
                id = '',
                name = '',
                email = '',
                rights = [
                    ''
                    ],
                disable_online_notifications = True,
                disable_digest_notifications = True,
                tour_done = [
                    ''
                    ],
                captcha = True,
        )
        """

    def testUserForAdmin(self):
        """Test UserForAdmin"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
