# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.defi_vanguard_v2_input import DefiVanguardV2Input

class TestDefiVanguardV2Input(unittest.TestCase):
    """DefiVanguardV2Input unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefiVanguardV2Input:
        """Test DefiVanguardV2Input
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefiVanguardV2Input`
        """
        model = DefiVanguardV2Input()
        if include_optional:
            return DefiVanguardV2Input(
                name = '',
                parameters = audithub_sdk.models.defi_vanguard_v2_parameters.DefiVanguardV2Parameters(
                    detector = [
                        ''
                        ], 
                    input_limit = [
                        ''
                        ], 
                    cross_version_triage = True, 
                    lang = 'solidity', 
                    solc = '', 
                    ignore_build_system = True, 
                    custom_detectors = null, )
            )
        else:
            return DefiVanguardV2Input(
                parameters = audithub_sdk.models.defi_vanguard_v2_parameters.DefiVanguardV2Parameters(
                    detector = [
                        ''
                        ], 
                    input_limit = [
                        ''
                        ], 
                    cross_version_triage = True, 
                    lang = 'solidity', 
                    solc = '', 
                    ignore_build_system = True, 
                    custom_detectors = null, ),
        )
        """

    def testDefiVanguardV2Input(self):
        """Test DefiVanguardV2Input"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
