# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.package_data import PackageData

class TestPackageData(unittest.TestCase):
    """PackageData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PackageData:
        """Test PackageData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PackageData`
        """
        model = PackageData()
        if include_optional:
            return PackageData(
                organization_name = '',
                user_limit = 56,
                projects = [
                    audithub_sdk.models.project_data.ProjectData(
                        definition = audithub_sdk.models.project_info.ProjectInfo(
                            name = '', 
                            project_root = '', 
                            env_vars = null, 
                            dependencies = null, 
                            build_system = 'hardhat', 
                            contents = [
                                'circom'
                                ], 
                            src_path = '', 
                            include_path = '', 
                            specs_path = '', 
                            hints_path = '', 
                            deployment_script_path = '', 
                            input_info = null, ), 
                        version = audithub_sdk.models.version_data.VersionData(
                            name = 'initial', 
                            digest = '', 
                            commit_hash = '', 
                            data_path = '', ), )
                    ],
                org_restrictions = [
                    audithub_sdk.models.organization_access_restriction.OrganizationAccessRestriction(
                        function = '', 
                        value = 56, 
                        detector = '', )
                    ],
                user_restrictions = [
                    audithub_sdk.models.user_access_restriction.UserAccessRestriction(
                        function = '', 
                        value = 56, 
                        detector = '', 
                        project_id = 56, )
                    ],
                subscription = audithub_sdk.models.package_subscription.PackageSubscription(
                    duration_months = 56, 
                    monthly_cpu_minutes = 56, 
                    storage_mb = 56, 
                    enforce_monthly_resource_consumption = True, )
            )
        else:
            return PackageData(
                organization_name = '',
                user_limit = 56,
                projects = [
                    audithub_sdk.models.project_data.ProjectData(
                        definition = audithub_sdk.models.project_info.ProjectInfo(
                            name = '', 
                            project_root = '', 
                            env_vars = null, 
                            dependencies = null, 
                            build_system = 'hardhat', 
                            contents = [
                                'circom'
                                ], 
                            src_path = '', 
                            include_path = '', 
                            specs_path = '', 
                            hints_path = '', 
                            deployment_script_path = '', 
                            input_info = null, ), 
                        version = audithub_sdk.models.version_data.VersionData(
                            name = 'initial', 
                            digest = '', 
                            commit_hash = '', 
                            data_path = '', ), )
                    ],
                org_restrictions = [
                    audithub_sdk.models.organization_access_restriction.OrganizationAccessRestriction(
                        function = '', 
                        value = 56, 
                        detector = '', )
                    ],
                user_restrictions = [
                    audithub_sdk.models.user_access_restriction.UserAccessRestriction(
                        function = '', 
                        value = 56, 
                        detector = '', 
                        project_id = 56, )
                    ],
                subscription = audithub_sdk.models.package_subscription.PackageSubscription(
                    duration_months = 56, 
                    monthly_cpu_minutes = 56, 
                    storage_mb = 56, 
                    enforce_monthly_resource_consumption = True, ),
        )
        """

    def testPackageData(self):
        """Test PackageData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
