# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.or_ca_parameters import OrCaParameters

class TestOrCaParameters(unittest.TestCase):
    """OrCaParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrCaParameters:
        """Test OrCaParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrCaParameters`
        """
        model = OrCaParameters()
        if include_optional:
            return OrCaParameters(
                disable_user_proxies = True,
                fuzz_pure = True,
                fuzz_targets = [
                    ''
                    ],
                fuzzing_blacklist = [
                    audithub_sdk.models.fuzzing_blacklist_entry.FuzzingBlacklistEntry(
                        contract = '', 
                        function = '', )
                    ],
                language = 'solidity',
                timeout = 56,
                fork_network = '',
                fork_block_number = 56
            )
        else:
            return OrCaParameters(
        )
        """

    def testOrCaParameters(self):
        """Test OrCaParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
