# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.public_configuration import PublicConfiguration

class TestPublicConfiguration(unittest.TestCase):
    """PublicConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicConfiguration:
        """Test PublicConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicConfiguration`
        """
        model = PublicConfiguration()
        if include_optional:
            return PublicConfiguration(
                fork_networks = [
                    audithub_sdk.models.fork_network_public.ForkNetworkPublic(
                        code = '', 
                        caption = '', )
                    ],
                vanguard_solc_versions = [
                    ''
                    ],
                vanguard_defi_detectors = [
                    audithub_sdk.models.vanguard_detector.VanguardDetector(
                        code = '', 
                        caption = '', 
                        tool = '', )
                    ],
                vanguard_v2_defi_detectors = [
                    audithub_sdk.models.vanguard_detector.VanguardDetector(
                        code = '', 
                        caption = '', 
                        tool = '', )
                    ],
                vanguard_zk_detectors = [
                    audithub_sdk.models.vanguard_detector.VanguardDetector(
                        code = '', 
                        caption = '', 
                        tool = '', )
                    ],
                vanguard_v2_zk_detectors = [
                    audithub_sdk.models.vanguard_detector.VanguardDetector(
                        code = '', 
                        caption = '', 
                        tool = '', )
                    ],
                node_versions = [
                    ''
                    ],
                workflow_steps = {
                    'key' : audithub_sdk.models.step_definition.StepDefinition(
                        caption = '', 
                        short_name = '', 
                        is_tool = True, )
                    },
                orca = {
                    'key' : null
                    },
                issue_configuration_options = audithub_sdk.models.issue_configuration_options.IssueConfigurationOptions(
                    likelihood = [
                        audithub_sdk.models.issue_likelihood.IssueLikelihood(
                            id = 56, 
                            caption = '', )
                        ], 
                    impact = [
                        audithub_sdk.models.issue_impact.IssueImpact(
                            id = 56, 
                            caption = '', )
                        ], 
                    severity = [
                        audithub_sdk.models.issue_severity.IssueSeverity(
                            id = 56, 
                            caption = '', )
                        ], 
                    status = [
                        audithub_sdk.models.issue_status.IssueStatus(
                            code = '', 
                            caption = '', 
                            is_final = True, )
                        ], ),
                available_tools = [
                    audithub_sdk.models.security_tool.SecurityTool(
                        id = 56, 
                        name = '', )
                    ],
                application_functions = [
                    audithub_sdk.models.application_function.ApplicationFunction(
                        name = '', 
                        caption = '', 
                        has_value = True, 
                        applicability = 56, 
                        per_project = True, 
                        per_detector = True, )
                    ],
                version_archive_size_limit = 56,
                onboarding_package = ''
            )
        else:
            return PublicConfiguration(
                fork_networks = [
                    audithub_sdk.models.fork_network_public.ForkNetworkPublic(
                        code = '', 
                        caption = '', )
                    ],
                vanguard_solc_versions = [
                    ''
                    ],
                vanguard_defi_detectors = [
                    audithub_sdk.models.vanguard_detector.VanguardDetector(
                        code = '', 
                        caption = '', 
                        tool = '', )
                    ],
                vanguard_v2_defi_detectors = [
                    audithub_sdk.models.vanguard_detector.VanguardDetector(
                        code = '', 
                        caption = '', 
                        tool = '', )
                    ],
                vanguard_zk_detectors = [
                    audithub_sdk.models.vanguard_detector.VanguardDetector(
                        code = '', 
                        caption = '', 
                        tool = '', )
                    ],
                vanguard_v2_zk_detectors = [
                    audithub_sdk.models.vanguard_detector.VanguardDetector(
                        code = '', 
                        caption = '', 
                        tool = '', )
                    ],
                node_versions = [
                    ''
                    ],
                workflow_steps = {
                    'key' : audithub_sdk.models.step_definition.StepDefinition(
                        caption = '', 
                        short_name = '', 
                        is_tool = True, )
                    },
                orca = {
                    'key' : null
                    },
                issue_configuration_options = audithub_sdk.models.issue_configuration_options.IssueConfigurationOptions(
                    likelihood = [
                        audithub_sdk.models.issue_likelihood.IssueLikelihood(
                            id = 56, 
                            caption = '', )
                        ], 
                    impact = [
                        audithub_sdk.models.issue_impact.IssueImpact(
                            id = 56, 
                            caption = '', )
                        ], 
                    severity = [
                        audithub_sdk.models.issue_severity.IssueSeverity(
                            id = 56, 
                            caption = '', )
                        ], 
                    status = [
                        audithub_sdk.models.issue_status.IssueStatus(
                            code = '', 
                            caption = '', 
                            is_final = True, )
                        ], ),
                available_tools = [
                    audithub_sdk.models.security_tool.SecurityTool(
                        id = 56, 
                        name = '', )
                    ],
                application_functions = [
                    audithub_sdk.models.application_function.ApplicationFunction(
                        name = '', 
                        caption = '', 
                        has_value = True, 
                        applicability = 56, 
                        per_project = True, 
                        per_detector = True, )
                    ],
                onboarding_package = '',
        )
        """

    def testPublicConfiguration(self):
        """Test PublicConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
