# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.issue_for_list import IssueForList

class TestIssueForList(unittest.TestCase):
    """IssueForList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IssueForList:
        """Test IssueForList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IssueForList`
        """
        model = IssueForList()
        if include_optional:
            return IssueForList(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = 56,
                gh_issue_url = '',
                gh_security_advisory_url = '',
                externally_shared = True,
                status = '',
                title = '',
                likelihood = 56,
                impact = 56,
                severity = 56
            )
        else:
            return IssueForList(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = 56,
                gh_issue_url = '',
                gh_security_advisory_url = '',
                externally_shared = True,
                status = '',
                title = '',
                likelihood = 56,
                impact = 56,
                severity = 56,
        )
        """

    def testIssueForList(self):
        """Test IssueForList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
