# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.zk_vanguard_parameters import ZKVanguardParameters

class TestZKVanguardParameters(unittest.TestCase):
    """ZKVanguardParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ZKVanguardParameters:
        """Test ZKVanguardParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ZKVanguardParameters`
        """
        model = ZKVanguardParameters()
        if include_optional:
            return ZKVanguardParameters(
                detector = [
                    ''
                    ],
                input_limit = [
                    ''
                    ],
                cross_version_triage = True,
                lang = 'circom'
            )
        else:
            return ZKVanguardParameters(
        )
        """

    def testZKVanguardParameters(self):
        """Test ZKVanguardParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
