# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.api.invitations_api import InvitationsApi


class TestInvitationsApi(unittest.IsolatedAsyncioTestCase):
    """InvitationsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = InvitationsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_delete_invitation_organizations_organization_id_invitations_invitation_id_delete(self) -> None:
        """Test case for delete_invitation_organizations_organization_id_invitations_invitation_id_delete

        Delete Invitation
        """
        pass

    async def test_get_invitation_organizations_organization_id_invitations_invitation_id_get(self) -> None:
        """Test case for get_invitation_organizations_organization_id_invitations_invitation_id_get

        Get Invitation
        """
        pass

    async def test_patch_invitation_organizations_organization_id_invitations_invitation_id_patch(self) -> None:
        """Test case for patch_invitation_organizations_organization_id_invitations_invitation_id_patch

        Patch Invitation
        """
        pass

    async def test_post_invitation_organizations_organization_id_invitations_post(self) -> None:
        """Test case for post_invitation_organizations_organization_id_invitations_post

        Post Invitation
        """
        pass


if __name__ == '__main__':
    unittest.main()
