# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.custom_detector_with_id import CustomDetectorWithId

class TestCustomDetectorWithId(unittest.TestCase):
    """CustomDetectorWithId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomDetectorWithId:
        """Test CustomDetectorWithId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomDetectorWithId`
        """
        model = CustomDetectorWithId()
        if include_optional:
            return CustomDetectorWithId(
                filename = '',
                contents = '',
                encoding = 'plain',
                id = 56
            )
        else:
            return CustomDetectorWithId(
                filename = '',
                contents = '',
                id = 56,
        )
        """

    def testCustomDetectorWithId(self):
        """Test CustomDetectorWithId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
