# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.api.versions_api import VersionsApi


class TestVersionsApi(unittest.TestCase):
    """VersionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VersionsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_version_organizations_organization_id_projects_project_id_versions_version_id_delete(self) -> None:
        """Test case for delete_version_organizations_organization_id_projects_project_id_versions_version_id_delete

        Delete Version
        """
        pass

    def test_get_comment_mutation_history_organizations_organization_id_projects_project_id_versions_version_id_comments_mutation_history_get(self) -> None:
        """Test case for get_comment_mutation_history_organizations_organization_id_projects_project_id_versions_version_id_comments_mutation_history_get

        Get Comment Mutation History
        """
        pass

    def test_get_latest_version_organizations_organization_id_projects_project_id_versions_latest_get(self) -> None:
        """Test case for get_latest_version_organizations_organization_id_projects_project_id_versions_latest_get

        Get Latest Version
        """
        pass

    def test_get_version_archive_organizations_organization_id_projects_project_id_versions_version_id_archive_get(self) -> None:
        """Test case for get_version_archive_organizations_organization_id_projects_project_id_versions_version_id_archive_get

        Get Version Archive
        """
        pass

    def test_get_version_catalog_organizations_organization_id_projects_project_id_versions_version_id_catalog_get(self) -> None:
        """Test case for get_version_catalog_organizations_organization_id_projects_project_id_versions_version_id_catalog_get

        Get Version Catalog
        """
        pass

    def test_get_version_comment_threads_organizations_organization_id_projects_project_id_versions_version_id_comment_threads_get(self) -> None:
        """Test case for get_version_comment_threads_organizations_organization_id_projects_project_id_versions_version_id_comment_threads_get

        Get Version Comment Threads
        """
        pass

    def test_get_version_comments_organizations_organization_id_projects_project_id_versions_version_id_comments_get(self) -> None:
        """Test case for get_version_comments_organizations_organization_id_projects_project_id_versions_version_id_comments_get

        Get Version Comments
        """
        pass

    def test_get_version_file_organizations_organization_id_projects_project_id_versions_version_id_file_get(self) -> None:
        """Test case for get_version_file_organizations_organization_id_projects_project_id_versions_version_id_file_get

        Get Version File
        """
        pass

    def test_get_version_findings_organizations_organization_id_projects_project_id_versions_version_id_findings_get(self) -> None:
        """Test case for get_version_findings_organizations_organization_id_projects_project_id_versions_version_id_findings_get

        Get Version Findings
        """
        pass

    def test_get_version_organizations_organization_id_projects_project_id_versions_version_id_get(self) -> None:
        """Test case for get_version_organizations_organization_id_projects_project_id_versions_version_id_get

        Get Version
        """
        pass

    def test_get_versions_organizations_organization_id_projects_project_id_versions_get(self) -> None:
        """Test case for get_versions_organizations_organization_id_projects_project_id_versions_get

        Get Versions
        """
        pass

    def test_patch_version_organizations_organization_id_projects_project_id_versions_version_id_patch(self) -> None:
        """Test case for patch_version_organizations_organization_id_projects_project_id_versions_version_id_patch

        Patch Version
        """
        pass

    def test_post_temp_version_organizations_organization_id_temp_versions_post(self) -> None:
        """Test case for post_temp_version_organizations_organization_id_temp_versions_post

        Post Temp Version
        """
        pass

    def test_post_temp_version_with_url_organizations_organization_id_temp_versions_url_post(self) -> None:
        """Test case for post_temp_version_with_url_organizations_organization_id_temp_versions_url_post

        Post Temp Version With Url
        """
        pass

    def test_post_version_organizations_organization_id_projects_project_id_versions_post(self) -> None:
        """Test case for post_version_organizations_organization_id_projects_project_id_versions_post

        Post Version
        """
        pass

    def test_post_version_with_url_organizations_organization_id_projects_project_id_versions_url_post(self) -> None:
        """Test case for post_version_with_url_organizations_organization_id_projects_project_id_versions_url_post

        Post Version With Url
        """
        pass


if __name__ == '__main__':
    unittest.main()
