# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.project_info_input import ProjectInfoInput

class TestProjectInfoInput(unittest.TestCase):
    """ProjectInfoInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectInfoInput:
        """Test ProjectInfoInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectInfoInput`
        """
        model = ProjectInfoInput()
        if include_optional:
            return ProjectInfoInput(
                name = '',
                project_root = '',
                env_vars = [
                    audithub_sdk.models.env_var.EnvVar(
                        name = '', 
                        value = '', )
                    ],
                dependencies = audithub_sdk.models.project_dependency.ProjectDependency(
                    npm = null, 
                    foundry = True, ),
                build_system = 'hardhat',
                contents = [
                    'circom'
                    ],
                src_path = '',
                include_path = '',
                specs_path = '',
                hints_path = '',
                deployment_script_path = '',
                input_info = None
            )
        else:
            return ProjectInfoInput(
                name = '',
                project_root = '',
                src_path = '',
                input_info = None,
        )
        """

    def testProjectInfoInput(self):
        """Test ProjectInfoInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
