# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.defi_vanguard_v2_parameters import DefiVanguardV2Parameters

class TestDefiVanguardV2Parameters(unittest.TestCase):
    """DefiVanguardV2Parameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefiVanguardV2Parameters:
        """Test DefiVanguardV2Parameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefiVanguardV2Parameters`
        """
        model = DefiVanguardV2Parameters()
        if include_optional:
            return DefiVanguardV2Parameters(
                detector = [
                    ''
                    ],
                input_limit = [
                    ''
                    ],
                cross_version_triage = True,
                lang = 'solidity',
                solc = '',
                ignore_build_system = True,
                custom_detectors = [
                    null
                    ]
            )
        else:
            return DefiVanguardV2Parameters(
        )
        """

    def testDefiVanguardV2Parameters(self):
        """Test DefiVanguardV2Parameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
