# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.package_subscription import PackageSubscription

class TestPackageSubscription(unittest.TestCase):
    """PackageSubscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PackageSubscription:
        """Test PackageSubscription
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PackageSubscription`
        """
        model = PackageSubscription()
        if include_optional:
            return PackageSubscription(
                duration_months = 56,
                monthly_cpu_minutes = 56,
                storage_mb = 56,
                enforce_monthly_resource_consumption = True
            )
        else:
            return PackageSubscription(
                duration_months = 56,
        )
        """

    def testPackageSubscription(self):
        """Test PackageSubscription"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
