# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.project_update_response import ProjectUpdateResponse

class TestProjectUpdateResponse(unittest.TestCase):
    """ProjectUpdateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectUpdateResponse:
        """Test ProjectUpdateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectUpdateResponse`
        """
        model = ProjectUpdateResponse()
        if include_optional:
            return ProjectUpdateResponse(
                id = 56,
                revision = '',
                message = '',
                success = True
            )
        else:
            return ProjectUpdateResponse(
                id = 56,
                revision = '',
                message = '',
                success = True,
        )
        """

    def testProjectUpdateResponse(self):
        """Test ProjectUpdateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
