# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.data import Data

class TestData(unittest.TestCase):
    """Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Data:
        """Test Data
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Data`
        """
        model = Data()
        if include_optional:
            return Data(
                id = 56,
                gh_issue_url = '',
                gh_security_advisory_url = '',
                status = '',
                revision_id = 56,
                resolutions = [
                    audithub_sdk.models.issue_resolution.IssueResolution(
                        resolution_pr = '0', 
                        resolution_commit = '', )
                    ],
                description = '',
                affected_files = [
                    audithub_sdk.models.source_reference.SourceReference(
                        version_id = 56, 
                        relative_path = '', 
                        line_from = 56, 
                        line_to = 56, )
                    ],
                type = [
                    56
                    ],
                title = '',
                likelihood = 56,
                impact = 56,
                severity = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                last_updated_by = '',
                externally_shared = True,
                promoted_findings = [
                    audithub_sdk.models.finding_reference.FindingReference(
                        task_id = 56, 
                        analysis_result_id = 56, 
                        finding_id = '', )
                    ],
                candidate_for_tool = [
                    56
                    ],
                raised_by = [
                    ''
                    ],
                poc_author = [
                    ''
                    ],
                document_authors = [
                    ''
                    ]
            )
        else:
            return Data(
                id = 56,
                gh_issue_url = '',
                gh_security_advisory_url = '',
                status = '',
                revision_id = 56,
                description = '',
                affected_files = [
                    audithub_sdk.models.source_reference.SourceReference(
                        version_id = 56, 
                        relative_path = '', 
                        line_from = 56, 
                        line_to = 56, )
                    ],
                type = [
                    56
                    ],
                title = '',
                likelihood = 56,
                impact = 56,
                severity = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                last_updated_by = '',
                externally_shared = True,
                promoted_findings = [
                    audithub_sdk.models.finding_reference.FindingReference(
                        task_id = 56, 
                        analysis_result_id = 56, 
                        finding_id = '', )
                    ],
                candidate_for_tool = [
                    56
                    ],
                raised_by = [
                    ''
                    ],
                poc_author = [
                    ''
                    ],
                document_authors = [
                    ''
                    ],
        )
        """

    def testData(self):
        """Test Data"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
