# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.task_admin import TaskAdmin

class TestTaskAdmin(unittest.TestCase):
    """TaskAdmin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskAdmin:
        """Test TaskAdmin
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskAdmin`
        """
        model = TaskAdmin()
        if include_optional:
            return TaskAdmin(
                id = 56,
                name = '',
                tool_name = '',
                tool_version = '',
                status = 'Queued',
                info_text = '',
                version_id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                deleted = True,
                findings_counters = {
                    'key' : 56
                    }
            )
        else:
            return TaskAdmin(
                id = 56,
                tool_name = '',
                tool_version = '',
                status = 'Queued',
                version_id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                deleted = True,
        )
        """

    def testTaskAdmin(self):
        """Test TaskAdmin"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
