# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.api.v_specs_org_lib_api import VSpecsOrgLibApi


class TestVSpecsOrgLibApi(unittest.TestCase):
    """VSpecsOrgLibApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VSpecsOrgLibApi()

    def tearDown(self) -> None:
        pass

    def test_delete_vspec_organizations_organization_id_vspecs_vspec_id_delete(self) -> None:
        """Test case for delete_vspec_organizations_organization_id_vspecs_vspec_id_delete

        Delete Vspec
        """
        pass

    def test_get_vspec_organizations_organization_id_vspecs_vspec_id_get(self) -> None:
        """Test case for get_vspec_organizations_organization_id_vspecs_vspec_id_get

        Get Vspec
        """
        pass

    def test_get_vspecs_organizations_organization_id_vspecs_get(self) -> None:
        """Test case for get_vspecs_organizations_organization_id_vspecs_get

        Get Vspecs
        """
        pass

    def test_post_vspec_organizations_organization_id_vspecs_post(self) -> None:
        """Test case for post_vspec_organizations_organization_id_vspecs_post

        Post Vspec
        """
        pass

    def test_put_vspec_organizations_organization_id_vspecs_vspec_id_put(self) -> None:
        """Test case for put_vspec_organizations_organization_id_vspecs_vspec_id_put

        Put Vspec
        """
        pass


if __name__ == '__main__':
    unittest.main()
