# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.model_tool_input import ModelToolInput

class TestModelToolInput(unittest.TestCase):
    """ModelToolInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelToolInput:
        """Test ModelToolInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelToolInput`
        """
        model = ModelToolInput()
        if include_optional:
            return ModelToolInput(
                name = '',
                phases = {
                    'key' : audithub_sdk.models.model_tool_phase_parameters.ModelToolPhaseParameters(
                        input_files = [
                            ''
                            ], 
                        exit_code = 56, 
                        sleep = 56, 
                        generate_findings = True, 
                        generate_accounting = True, 
                        findings_completed = True, 
                        findings_error_message = '', 
                        findings_warning = 56, 
                        findings_low = 56, 
                        findings_medium = 56, 
                        findings_high = 56, 
                        findings_critical = 56, )
                    }
            )
        else:
            return ModelToolInput(
        )
        """

    def testModelToolInput(self):
        """Test ModelToolInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
