# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.models.version_admin import VersionAdmin

class TestVersionAdmin(unittest.TestCase):
    """VersionAdmin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VersionAdmin:
        """Test VersionAdmin
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VersionAdmin`
        """
        model = VersionAdmin()
        if include_optional:
            return VersionAdmin(
                id = 56,
                name = '',
                archive_catalog = audithub_sdk.models.directory.Directory(
                    name = '', 
                    type = 'd', 
                    contents = [
                        null
                        ], ),
                archive_abi = [
                    null
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                input_info = None,
                project_revision_hash = '',
                digest = '',
                commit_hash = '',
                is_deployed = True,
                deleted = True,
                created_by = '',
                organization_id = 56,
                project_id = 56
            )
        else:
            return VersionAdmin(
                id = 56,
                name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                input_info = None,
                project_revision_hash = '',
                digest = '',
                commit_hash = '',
                is_deployed = True,
                deleted = True,
                created_by = '',
                organization_id = 56,
                project_id = 56,
        )
        """

    def testVersionAdmin(self):
        """Test VersionAdmin"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
