# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from audithub_sdk.api.custom_detectors_std_lib_api import CustomDetectorsStdLibApi


class TestCustomDetectorsStdLibApi(unittest.TestCase):
    """CustomDetectorsStdLibApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomDetectorsStdLibApi()

    def tearDown(self) -> None:
        pass

    def test_get_custom_detectors_library_custom_detectors_library_get(self) -> None:
        """Test case for get_custom_detectors_library_custom_detectors_library_get

        Get Custom Detectors Library
        """
        pass

    def test_get_custom_detectors_library_version_custom_detectors_library_version_id_get(self) -> None:
        """Test case for get_custom_detectors_library_version_custom_detectors_library_version_id_get

        Get Custom Detectors Library Version
        """
        pass


if __name__ == '__main__':
    unittest.main()
