# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from audithub_sdk.models.machine_info import MachineInfo
from typing import Optional, Set
from typing_extensions import Self

class AccountingData(BaseModel):
    """
    AccountingData
    """ # noqa: E501
    step_code: Optional[StrictStr] = None
    container_name: Optional[StrictStr] = None
    system: StrictBool
    created_at: datetime
    entry_timestamp: datetime
    entry_text: Optional[StrictStr]
    entry_type: StrictStr
    entry_unit: StrictStr
    entry_value: Annotated[str, Field(strict=True)]
    machine_info: Optional[MachineInfo] = None
    __properties: ClassVar[List[str]] = ["step_code", "container_name", "system", "created_at", "entry_timestamp", "entry_text", "entry_type", "entry_unit", "entry_value", "machine_info"]

    @field_validator('entry_value')
    def entry_value_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$", value):
            raise ValueError(r"must validate the regular expression /^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountingData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of machine_info
        if self.machine_info:
            _dict['machine_info'] = self.machine_info.to_dict()
        # set to None if step_code (nullable) is None
        # and model_fields_set contains the field
        if self.step_code is None and "step_code" in self.model_fields_set:
            _dict['step_code'] = None

        # set to None if container_name (nullable) is None
        # and model_fields_set contains the field
        if self.container_name is None and "container_name" in self.model_fields_set:
            _dict['container_name'] = None

        # set to None if entry_text (nullable) is None
        # and model_fields_set contains the field
        if self.entry_text is None and "entry_text" in self.model_fields_set:
            _dict['entry_text'] = None

        # set to None if machine_info (nullable) is None
        # and model_fields_set contains the field
        if self.machine_info is None and "machine_info" in self.model_fields_set:
            _dict['machine_info'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountingData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "step_code": obj.get("step_code"),
            "container_name": obj.get("container_name"),
            "system": obj.get("system"),
            "created_at": obj.get("created_at"),
            "entry_timestamp": obj.get("entry_timestamp"),
            "entry_text": obj.get("entry_text"),
            "entry_type": obj.get("entry_type"),
            "entry_unit": obj.get("entry_unit"),
            "entry_value": obj.get("entry_value"),
            "machine_info": MachineInfo.from_dict(obj["machine_info"]) if obj.get("machine_info") is not None else None
        })
        return _obj


