# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from audithub_sdk.models.included_user_info import IncludedUserInfo
from audithub_sdk.models.invited_user import InvitedUser
from audithub_sdk.models.registered_user import RegisteredUser
from typing import Optional, Set
from typing_extensions import Self

class ActiveOrganizationUsers(BaseModel):
    """
    ActiveOrganizationUsers
    """ # noqa: E501
    registered: List[RegisteredUser]
    invited: List[InvitedUser]
    users: Dict[str, IncludedUserInfo]
    __properties: ClassVar[List[str]] = ["registered", "invited", "users"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActiveOrganizationUsers from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in registered (list)
        _items = []
        if self.registered:
            for _item_registered in self.registered:
                if _item_registered:
                    _items.append(_item_registered.to_dict())
            _dict['registered'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in invited (list)
        _items = []
        if self.invited:
            for _item_invited in self.invited:
                if _item_invited:
                    _items.append(_item_invited.to_dict())
            _dict['invited'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in users (dict)
        _field_dict = {}
        if self.users:
            for _key_users in self.users:
                if self.users[_key_users]:
                    _field_dict[_key_users] = self.users[_key_users].to_dict()
            _dict['users'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActiveOrganizationUsers from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "registered": [RegisteredUser.from_dict(_item) for _item in obj["registered"]] if obj.get("registered") is not None else None,
            "invited": [InvitedUser.from_dict(_item) for _item in obj["invited"]] if obj.get("invited") is not None else None,
            "users": dict(
                (_k, IncludedUserInfo.from_dict(_v))
                for _k, _v in obj["users"].items()
            )
            if obj.get("users") is not None
            else None
        })
        return _obj


