# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from audithub_sdk.models.extra_function_arguments import ExtraFunctionArguments
from typing import Optional, Set
from typing_extensions import Self

class IssueStateTransitionFunction(BaseModel):
    """
    IssueStateTransitionFunction
    """ # noqa: E501
    id: StrictInt
    code: StrictStr
    caption: StrictStr
    has_comment: StrictBool
    has_pr: StrictBool
    optional_comment: StrictBool
    pre_populated_extra: Optional[ExtraFunctionArguments]
    available_to_developers: StrictBool
    __properties: ClassVar[List[str]] = ["id", "code", "caption", "has_comment", "has_pr", "optional_comment", "pre_populated_extra", "available_to_developers"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IssueStateTransitionFunction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pre_populated_extra
        if self.pre_populated_extra:
            _dict['pre_populated_extra'] = self.pre_populated_extra.to_dict()
        # set to None if pre_populated_extra (nullable) is None
        # and model_fields_set contains the field
        if self.pre_populated_extra is None and "pre_populated_extra" in self.model_fields_set:
            _dict['pre_populated_extra'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IssueStateTransitionFunction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "code": obj.get("code"),
            "caption": obj.get("caption"),
            "has_comment": obj.get("has_comment"),
            "has_pr": obj.get("has_pr"),
            "optional_comment": obj.get("optional_comment"),
            "pre_populated_extra": ExtraFunctionArguments.from_dict(obj["pre_populated_extra"]) if obj.get("pre_populated_extra") is not None else None,
            "available_to_developers": obj.get("available_to_developers")
        })
        return _obj


