# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from audithub_sdk.models.issue_impact import IssueImpact
from audithub_sdk.models.issue_likelihood import IssueLikelihood
from audithub_sdk.models.issue_severity import IssueSeverity
from audithub_sdk.models.issue_status import IssueStatus
from typing import Optional, Set
from typing_extensions import Self

class IssueConfigurationOptions(BaseModel):
    """
    IssueConfigurationOptions
    """ # noqa: E501
    likelihood: List[IssueLikelihood]
    impact: List[IssueImpact]
    severity: List[IssueSeverity]
    status: List[IssueStatus]
    __properties: ClassVar[List[str]] = ["likelihood", "impact", "severity", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IssueConfigurationOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in likelihood (list)
        _items = []
        if self.likelihood:
            for _item_likelihood in self.likelihood:
                if _item_likelihood:
                    _items.append(_item_likelihood.to_dict())
            _dict['likelihood'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in impact (list)
        _items = []
        if self.impact:
            for _item_impact in self.impact:
                if _item_impact:
                    _items.append(_item_impact.to_dict())
            _dict['impact'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in severity (list)
        _items = []
        if self.severity:
            for _item_severity in self.severity:
                if _item_severity:
                    _items.append(_item_severity.to_dict())
            _dict['severity'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in status (list)
        _items = []
        if self.status:
            for _item_status in self.status:
                if _item_status:
                    _items.append(_item_status.to_dict())
            _dict['status'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IssueConfigurationOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "likelihood": [IssueLikelihood.from_dict(_item) for _item in obj["likelihood"]] if obj.get("likelihood") is not None else None,
            "impact": [IssueImpact.from_dict(_item) for _item in obj["impact"]] if obj.get("impact") is not None else None,
            "severity": [IssueSeverity.from_dict(_item) for _item in obj["severity"]] if obj.get("severity") is not None else None,
            "status": [IssueStatus.from_dict(_item) for _item in obj["status"]] if obj.get("status") is not None else None
        })
        return _obj


