# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ModelToolPhaseParameters(BaseModel):
    """
    ModelToolPhaseParameters
    """ # noqa: E501
    input_files: Optional[List[StrictStr]] = None
    exit_code: Optional[StrictInt] = None
    sleep: Optional[StrictInt] = None
    generate_findings: Optional[StrictBool] = None
    generate_accounting: Optional[StrictBool] = None
    findings_completed: Optional[StrictBool] = None
    findings_error_message: Optional[StrictStr] = None
    findings_warning: Optional[StrictInt] = None
    findings_low: Optional[StrictInt] = None
    findings_medium: Optional[StrictInt] = None
    findings_high: Optional[StrictInt] = None
    findings_critical: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["input_files", "exit_code", "sleep", "generate_findings", "generate_accounting", "findings_completed", "findings_error_message", "findings_warning", "findings_low", "findings_medium", "findings_high", "findings_critical"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelToolPhaseParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if input_files (nullable) is None
        # and model_fields_set contains the field
        if self.input_files is None and "input_files" in self.model_fields_set:
            _dict['input_files'] = None

        # set to None if exit_code (nullable) is None
        # and model_fields_set contains the field
        if self.exit_code is None and "exit_code" in self.model_fields_set:
            _dict['exit_code'] = None

        # set to None if sleep (nullable) is None
        # and model_fields_set contains the field
        if self.sleep is None and "sleep" in self.model_fields_set:
            _dict['sleep'] = None

        # set to None if generate_findings (nullable) is None
        # and model_fields_set contains the field
        if self.generate_findings is None and "generate_findings" in self.model_fields_set:
            _dict['generate_findings'] = None

        # set to None if generate_accounting (nullable) is None
        # and model_fields_set contains the field
        if self.generate_accounting is None and "generate_accounting" in self.model_fields_set:
            _dict['generate_accounting'] = None

        # set to None if findings_completed (nullable) is None
        # and model_fields_set contains the field
        if self.findings_completed is None and "findings_completed" in self.model_fields_set:
            _dict['findings_completed'] = None

        # set to None if findings_error_message (nullable) is None
        # and model_fields_set contains the field
        if self.findings_error_message is None and "findings_error_message" in self.model_fields_set:
            _dict['findings_error_message'] = None

        # set to None if findings_warning (nullable) is None
        # and model_fields_set contains the field
        if self.findings_warning is None and "findings_warning" in self.model_fields_set:
            _dict['findings_warning'] = None

        # set to None if findings_low (nullable) is None
        # and model_fields_set contains the field
        if self.findings_low is None and "findings_low" in self.model_fields_set:
            _dict['findings_low'] = None

        # set to None if findings_medium (nullable) is None
        # and model_fields_set contains the field
        if self.findings_medium is None and "findings_medium" in self.model_fields_set:
            _dict['findings_medium'] = None

        # set to None if findings_high (nullable) is None
        # and model_fields_set contains the field
        if self.findings_high is None and "findings_high" in self.model_fields_set:
            _dict['findings_high'] = None

        # set to None if findings_critical (nullable) is None
        # and model_fields_set contains the field
        if self.findings_critical is None and "findings_critical" in self.model_fields_set:
            _dict['findings_critical'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelToolPhaseParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "input_files": obj.get("input_files"),
            "exit_code": obj.get("exit_code"),
            "sleep": obj.get("sleep"),
            "generate_findings": obj.get("generate_findings"),
            "generate_accounting": obj.get("generate_accounting"),
            "findings_completed": obj.get("findings_completed"),
            "findings_error_message": obj.get("findings_error_message"),
            "findings_warning": obj.get("findings_warning"),
            "findings_low": obj.get("findings_low"),
            "findings_medium": obj.get("findings_medium"),
            "findings_high": obj.get("findings_high"),
            "findings_critical": obj.get("findings_critical")
        })
        return _obj


