# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from audithub_sdk.models.organization_access_restriction import OrganizationAccessRestriction
from audithub_sdk.models.package_subscription import PackageSubscription
from audithub_sdk.models.user_access_restriction import UserAccessRestriction
from typing import Optional, Set
from typing_extensions import Self

class NewOrganizationPackage(BaseModel):
    """
    NewOrganizationPackage
    """ # noqa: E501
    org_restrictions: Optional[List[OrganizationAccessRestriction]] = None
    user_restrictions: Optional[List[UserAccessRestriction]] = None
    user_limit: Optional[StrictInt] = None
    subscription: PackageSubscription
    org_name: Optional[StrictStr] = Field(default='demo-organization-{email}', description="Template name for creating new organization. Available keywords to be replaced are user attributes 'name', 'email', 'id' and 'timestamp' that the organization gets created")
    name: StrictStr
    __properties: ClassVar[List[str]] = ["org_restrictions", "user_restrictions", "user_limit", "subscription", "org_name", "name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NewOrganizationPackage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in org_restrictions (list)
        _items = []
        if self.org_restrictions:
            for _item_org_restrictions in self.org_restrictions:
                if _item_org_restrictions:
                    _items.append(_item_org_restrictions.to_dict())
            _dict['org_restrictions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in user_restrictions (list)
        _items = []
        if self.user_restrictions:
            for _item_user_restrictions in self.user_restrictions:
                if _item_user_restrictions:
                    _items.append(_item_user_restrictions.to_dict())
            _dict['user_restrictions'] = _items
        # override the default output from pydantic by calling `to_dict()` of subscription
        if self.subscription:
            _dict['subscription'] = self.subscription.to_dict()
        # set to None if org_restrictions (nullable) is None
        # and model_fields_set contains the field
        if self.org_restrictions is None and "org_restrictions" in self.model_fields_set:
            _dict['org_restrictions'] = None

        # set to None if user_restrictions (nullable) is None
        # and model_fields_set contains the field
        if self.user_restrictions is None and "user_restrictions" in self.model_fields_set:
            _dict['user_restrictions'] = None

        # set to None if user_limit (nullable) is None
        # and model_fields_set contains the field
        if self.user_limit is None and "user_limit" in self.model_fields_set:
            _dict['user_limit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NewOrganizationPackage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "org_restrictions": [OrganizationAccessRestriction.from_dict(_item) for _item in obj["org_restrictions"]] if obj.get("org_restrictions") is not None else None,
            "user_restrictions": [UserAccessRestriction.from_dict(_item) for _item in obj["user_restrictions"]] if obj.get("user_restrictions") is not None else None,
            "user_limit": obj.get("user_limit"),
            "subscription": PackageSubscription.from_dict(obj["subscription"]) if obj.get("subscription") is not None else None,
            "org_name": obj.get("org_name") if obj.get("org_name") is not None else 'demo-organization-{email}',
            "name": obj.get("name")
        })
        return _obj


