# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from audithub_sdk.models.or_ca_parameters import OrCaParameters
from audithub_sdk.models.root_model_list_union_hint_from_version_hint_from_standard_library_hint_from_organization_library_hint_ad_hoc_inner import RootModelListUnionHintFromVersionHintFromStandardLibraryHintFromOrganizationLibraryHintAdHocInner
from audithub_sdk.models.root_model_list_union_v_spec_from_version_v_spec_from_standard_library_v_spec_from_organization_library_v_spec_ad_hoc_inner import RootModelListUnionVSpecFromVersionVSpecFromStandardLibraryVSpecFromOrganizationLibraryVSpecAdHocInner
from typing import Optional, Set
from typing_extensions import Self

class OrCaInput(BaseModel):
    """
    OrCaInput
    """ # noqa: E501
    specs_override: List[RootModelListUnionVSpecFromVersionVSpecFromStandardLibraryVSpecFromOrganizationLibraryVSpecAdHocInner] = Field(description="This task will will run against these specs.")
    hints_override: Optional[List[RootModelListUnionHintFromVersionHintFromStandardLibraryHintFromOrganizationLibraryHintAdHocInner]] = None
    deployment_script_path_override: Optional[StrictStr] = None
    on_chain: Optional[StrictBool] = Field(default=False, description="Specifies whether to enable on chain fuzzing")
    deployment_info_file: Optional[StrictStr] = None
    name: Optional[StrictStr] = Field(default=None, description="An optional name for this task. If not specified, the current time in UTC will be used.")
    parameters: OrCaParameters = Field(description="The parameters to pass to OrCa")
    __properties: ClassVar[List[str]] = ["specs_override", "hints_override", "deployment_script_path_override", "on_chain", "deployment_info_file", "name", "parameters"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrCaInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in specs_override (list)
        _items = []
        if self.specs_override:
            for _item_specs_override in self.specs_override:
                if _item_specs_override:
                    _items.append(_item_specs_override.to_dict())
            _dict['specs_override'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in hints_override (list)
        _items = []
        if self.hints_override:
            for _item_hints_override in self.hints_override:
                if _item_hints_override:
                    _items.append(_item_hints_override.to_dict())
            _dict['hints_override'] = _items
        # override the default output from pydantic by calling `to_dict()` of parameters
        if self.parameters:
            _dict['parameters'] = self.parameters.to_dict()
        # set to None if hints_override (nullable) is None
        # and model_fields_set contains the field
        if self.hints_override is None and "hints_override" in self.model_fields_set:
            _dict['hints_override'] = None

        # set to None if deployment_script_path_override (nullable) is None
        # and model_fields_set contains the field
        if self.deployment_script_path_override is None and "deployment_script_path_override" in self.model_fields_set:
            _dict['deployment_script_path_override'] = None

        # set to None if deployment_info_file (nullable) is None
        # and model_fields_set contains the field
        if self.deployment_info_file is None and "deployment_info_file" in self.model_fields_set:
            _dict['deployment_info_file'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrCaInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "specs_override": [RootModelListUnionVSpecFromVersionVSpecFromStandardLibraryVSpecFromOrganizationLibraryVSpecAdHocInner.from_dict(_item) for _item in obj["specs_override"]] if obj.get("specs_override") is not None else None,
            "hints_override": [RootModelListUnionHintFromVersionHintFromStandardLibraryHintFromOrganizationLibraryHintAdHocInner.from_dict(_item) for _item in obj["hints_override"]] if obj.get("hints_override") is not None else None,
            "deployment_script_path_override": obj.get("deployment_script_path_override"),
            "on_chain": obj.get("on_chain") if obj.get("on_chain") is not None else False,
            "deployment_info_file": obj.get("deployment_info_file"),
            "name": obj.get("name"),
            "parameters": OrCaParameters.from_dict(obj["parameters"]) if obj.get("parameters") is not None else None
        })
        return _obj


