# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TaskAdmin(BaseModel):
    """
    TaskAdmin
    """ # noqa: E501
    id: StrictInt
    name: Optional[StrictStr] = None
    tool_name: StrictStr
    tool_version: StrictStr
    status: StrictStr
    info_text: Optional[StrictStr] = None
    version_id: StrictInt
    created_at: datetime
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    created_by: StrictStr
    deleted: StrictBool = Field(description="If true, then the task has been soft-deleted.")
    findings_counters: Optional[Dict[str, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["id", "name", "tool_name", "tool_version", "status", "info_text", "version_id", "created_at", "started_at", "finished_at", "created_by", "deleted", "findings_counters"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Queued', 'Running', 'Finished', 'Failed', 'Error', 'Canceled', 'Pending', 'Succeeded', 'Skipped', 'Omitted']):
            raise ValueError("must be one of enum values ('Queued', 'Running', 'Finished', 'Failed', 'Error', 'Canceled', 'Pending', 'Succeeded', 'Skipped', 'Omitted')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaskAdmin from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if info_text (nullable) is None
        # and model_fields_set contains the field
        if self.info_text is None and "info_text" in self.model_fields_set:
            _dict['info_text'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        # set to None if finished_at (nullable) is None
        # and model_fields_set contains the field
        if self.finished_at is None and "finished_at" in self.model_fields_set:
            _dict['finished_at'] = None

        # set to None if findings_counters (nullable) is None
        # and model_fields_set contains the field
        if self.findings_counters is None and "findings_counters" in self.model_fields_set:
            _dict['findings_counters'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaskAdmin from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "tool_name": obj.get("tool_name"),
            "tool_version": obj.get("tool_version"),
            "status": obj.get("status"),
            "info_text": obj.get("info_text"),
            "version_id": obj.get("version_id"),
            "created_at": obj.get("created_at"),
            "started_at": obj.get("started_at"),
            "finished_at": obj.get("finished_at"),
            "created_by": obj.get("created_by"),
            "deleted": obj.get("deleted"),
            "findings_counters": obj.get("findings_counters")
        })
        return _obj


