# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from audithub_sdk.models.subject import Subject
from typing import Optional, Set
from typing_extensions import Self

class Thread(BaseModel):
    """
    Thread
    """ # noqa: E501
    project_id: StrictInt
    version_id: Optional[StrictInt] = None
    type: StrictStr
    subject: Subject
    title: Optional[StrictStr] = None
    id: StrictInt
    created_at: datetime
    created_by: StrictStr
    commenter_ids: Optional[List[StrictStr]] = None
    resolved: Optional[StrictBool] = False
    resolved_at: Optional[datetime] = None
    resolved_by: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["project_id", "version_id", "type", "subject", "title", "id", "created_at", "created_by", "commenter_ids", "resolved", "resolved_at", "resolved_by"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['note', 'question', 'potential_finding', 'issue']):
            raise ValueError("must be one of enum values ('note', 'question', 'potential_finding', 'issue')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Thread from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of subject
        if self.subject:
            _dict['subject'] = self.subject.to_dict()
        # set to None if version_id (nullable) is None
        # and model_fields_set contains the field
        if self.version_id is None and "version_id" in self.model_fields_set:
            _dict['version_id'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if commenter_ids (nullable) is None
        # and model_fields_set contains the field
        if self.commenter_ids is None and "commenter_ids" in self.model_fields_set:
            _dict['commenter_ids'] = None

        # set to None if resolved_at (nullable) is None
        # and model_fields_set contains the field
        if self.resolved_at is None and "resolved_at" in self.model_fields_set:
            _dict['resolved_at'] = None

        # set to None if resolved_by (nullable) is None
        # and model_fields_set contains the field
        if self.resolved_by is None and "resolved_by" in self.model_fields_set:
            _dict['resolved_by'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Thread from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "project_id": obj.get("project_id"),
            "version_id": obj.get("version_id"),
            "type": obj.get("type"),
            "subject": Subject.from_dict(obj["subject"]) if obj.get("subject") is not None else None,
            "title": obj.get("title"),
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "commenter_ids": obj.get("commenter_ids"),
            "resolved": obj.get("resolved") if obj.get("resolved") is not None else False,
            "resolved_at": obj.get("resolved_at"),
            "resolved_by": obj.get("resolved_by")
        })
        return _obj


