# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class VersionPatch(BaseModel):
    """
    VersionPatch
    """ # noqa: E501
    delete: Optional[StrictBool] = None
    name: Optional[StrictStr] = None
    commit_hash: Optional[StrictStr] = None
    project_revision_hash: Optional[StrictStr] = None
    is_deployed: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["delete", "name", "commit_hash", "project_revision_hash", "is_deployed"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VersionPatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if delete (nullable) is None
        # and model_fields_set contains the field
        if self.delete is None and "delete" in self.model_fields_set:
            _dict['delete'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if commit_hash (nullable) is None
        # and model_fields_set contains the field
        if self.commit_hash is None and "commit_hash" in self.model_fields_set:
            _dict['commit_hash'] = None

        # set to None if project_revision_hash (nullable) is None
        # and model_fields_set contains the field
        if self.project_revision_hash is None and "project_revision_hash" in self.model_fields_set:
            _dict['project_revision_hash'] = None

        # set to None if is_deployed (nullable) is None
        # and model_fields_set contains the field
        if self.is_deployed is None and "is_deployed" in self.model_fields_set:
            _dict['is_deployed'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VersionPatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "delete": obj.get("delete"),
            "name": obj.get("name"),
            "commit_hash": obj.get("commit_hash"),
            "project_revision_hash": obj.get("project_revision_hash"),
            "is_deployed": obj.get("is_deployed")
        })
        return _obj


