# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from audithub_sdk.models.directory import Directory
from audithub_sdk.models.input_info import InputInfo
from typing import Optional, Set
from typing_extensions import Self

class Version(BaseModel):
    """
    Version
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    archive_catalog: Optional[Directory] = None
    archive_abi: Optional[List[Any]] = None
    created_at: datetime
    input_info: InputInfo
    project_revision_hash: StrictStr
    digest: Optional[StrictStr]
    commit_hash: Optional[StrictStr]
    is_deployed: StrictBool
    __properties: ClassVar[List[str]] = ["id", "name", "archive_catalog", "archive_abi", "created_at", "input_info", "project_revision_hash", "digest", "commit_hash", "is_deployed"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Version from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of archive_catalog
        if self.archive_catalog:
            _dict['archive_catalog'] = self.archive_catalog.to_dict()
        # override the default output from pydantic by calling `to_dict()` of input_info
        if self.input_info:
            _dict['input_info'] = self.input_info.to_dict()
        # set to None if archive_catalog (nullable) is None
        # and model_fields_set contains the field
        if self.archive_catalog is None and "archive_catalog" in self.model_fields_set:
            _dict['archive_catalog'] = None

        # set to None if archive_abi (nullable) is None
        # and model_fields_set contains the field
        if self.archive_abi is None and "archive_abi" in self.model_fields_set:
            _dict['archive_abi'] = None

        # set to None if digest (nullable) is None
        # and model_fields_set contains the field
        if self.digest is None and "digest" in self.model_fields_set:
            _dict['digest'] = None

        # set to None if commit_hash (nullable) is None
        # and model_fields_set contains the field
        if self.commit_hash is None and "commit_hash" in self.model_fields_set:
            _dict['commit_hash'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Version from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "archive_catalog": Directory.from_dict(obj["archive_catalog"]) if obj.get("archive_catalog") is not None else None,
            "archive_abi": obj.get("archive_abi"),
            "created_at": obj.get("created_at"),
            "input_info": InputInfo.from_dict(obj["input_info"]) if obj.get("input_info") is not None else None,
            "project_revision_hash": obj.get("project_revision_hash"),
            "digest": obj.get("digest"),
            "commit_hash": obj.get("commit_hash"),
            "is_deployed": obj.get("is_deployed")
        })
        return _obj


